# Generated by Django 5.2.3 on 2025-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('humedad', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
