# Generated by Django 5.1.2 on 2025-06-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hist',
            options={'get_latest_by': 'fecha_hora'},
        ),
        migrations.AddField(
            model_name='hist',
            name='presion',
            field=models.IntegerField(default=70000),
            preserve_default=False,
        ),
    ]
